version: '3'

services:
  loadbalancer:
    build: .
    container_name: lb-haproxy
    ports:
      - 80:80
      - 8404:8404
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  nginx1:
    build: ./CI-framework1/.

  wen2:
    build: ./CI-framework2/.


  nginx3:
    build: ./CI-framework3/.
